name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        brew install ffmpeg
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build macOS app
      run: |
        pyinstaller RedSea.spec
    
    - name: Create DMG (optional)
      run: |
        mkdir -p dist/dmg
        cp -R dist/RedSea.app dist/dmg/
        hdiutil create -volname "RedSea" -srcfolder dist/dmg -ov -format UDZO dist/RedSea.dmg
    
    - name: Upload app as artifact
      uses: actions/upload-artifact@v3
      with:
        name: RedSea-macOS
        path: |
          dist/RedSea.app
          dist/RedSea.dmg
        retention-days: 30
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/RedSea.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}